// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gcpc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HookPhaseV1 specifies when a hook fires relative to command execution.
type HookPhaseV1 int32

const (
	HookPhaseV1_HOOK_PHASE_UNSPECIFIED HookPhaseV1 = 0
	HookPhaseV1_HOOK_PHASE_PRE         HookPhaseV1 = 1 // before command execution
	HookPhaseV1_HOOK_PHASE_POST        HookPhaseV1 = 2 // after command execution
)

// Enum value maps for HookPhaseV1.
var (
	HookPhaseV1_name = map[int32]string{
		0: "HOOK_PHASE_UNSPECIFIED",
		1: "HOOK_PHASE_PRE",
		2: "HOOK_PHASE_POST",
	}
	HookPhaseV1_value = map[string]int32{
		"HOOK_PHASE_UNSPECIFIED": 0,
		"HOOK_PHASE_PRE":         1,
		"HOOK_PHASE_POST":        2,
	}
)

func (x HookPhaseV1) Enum() *HookPhaseV1 {
	p := new(HookPhaseV1)
	*p = x
	return p
}

func (x HookPhaseV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HookPhaseV1) Descriptor() protoreflect.EnumDescriptor {
	return file_gcpc_proto_enumTypes[0].Descriptor()
}

func (HookPhaseV1) Type() protoreflect.EnumType {
	return &file_gcpc_proto_enumTypes[0]
}

func (x HookPhaseV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HookPhaseV1.Descriptor instead.
func (HookPhaseV1) EnumDescriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{0}
}

// EnvelopeV1 wraps every message on the wire.
// Framing: [4-byte big-endian length][serialized EnvelopeV1]
type EnvelopeV1 struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // protocol version, must be 1
	Id      uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`           // correlation ID for request/response pairing
	// Types that are valid to be assigned to Payload:
	//
	//	*EnvelopeV1_Register
	//	*EnvelopeV1_RegisterAck
	//	*EnvelopeV1_HealthCheck
	//	*EnvelopeV1_HealthResponse
	//	*EnvelopeV1_Shutdown
	//	*EnvelopeV1_ShutdownAck
	//	*EnvelopeV1_CommandRequest
	//	*EnvelopeV1_CommandResponse
	//	*EnvelopeV1_HookRequest
	//	*EnvelopeV1_HookResponse
	//	*EnvelopeV1_ServerQuery
	//	*EnvelopeV1_ServerQueryResponse
	Payload       isEnvelopeV1_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeV1) Reset() {
	*x = EnvelopeV1{}
	mi := &file_gcpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeV1) ProtoMessage() {}

func (x *EnvelopeV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeV1.ProtoReflect.Descriptor instead.
func (*EnvelopeV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{0}
}

func (x *EnvelopeV1) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EnvelopeV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnvelopeV1) GetPayload() isEnvelopeV1_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnvelopeV1) GetRegister() *RegisterV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *EnvelopeV1) GetRegisterAck() *RegisterAckV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *EnvelopeV1) GetHealthCheck() *HealthCheckV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

func (x *EnvelopeV1) GetHealthResponse() *HealthResponseV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_HealthResponse); ok {
			return x.HealthResponse
		}
	}
	return nil
}

func (x *EnvelopeV1) GetShutdown() *ShutdownV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *EnvelopeV1) GetShutdownAck() *ShutdownAckV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_ShutdownAck); ok {
			return x.ShutdownAck
		}
	}
	return nil
}

func (x *EnvelopeV1) GetCommandRequest() *CommandRequestV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_CommandRequest); ok {
			return x.CommandRequest
		}
	}
	return nil
}

func (x *EnvelopeV1) GetCommandResponse() *CommandResponseV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_CommandResponse); ok {
			return x.CommandResponse
		}
	}
	return nil
}

func (x *EnvelopeV1) GetHookRequest() *HookRequestV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_HookRequest); ok {
			return x.HookRequest
		}
	}
	return nil
}

func (x *EnvelopeV1) GetHookResponse() *HookResponseV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_HookResponse); ok {
			return x.HookResponse
		}
	}
	return nil
}

func (x *EnvelopeV1) GetServerQuery() *ServerQueryV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_ServerQuery); ok {
			return x.ServerQuery
		}
	}
	return nil
}

func (x *EnvelopeV1) GetServerQueryResponse() *ServerQueryResponseV1 {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeV1_ServerQueryResponse); ok {
			return x.ServerQueryResponse
		}
	}
	return nil
}

type isEnvelopeV1_Payload interface {
	isEnvelopeV1_Payload()
}

type EnvelopeV1_Register struct {
	Register *RegisterV1 `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type EnvelopeV1_RegisterAck struct {
	RegisterAck *RegisterAckV1 `protobuf:"bytes,11,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type EnvelopeV1_HealthCheck struct {
	HealthCheck *HealthCheckV1 `protobuf:"bytes,20,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

type EnvelopeV1_HealthResponse struct {
	HealthResponse *HealthResponseV1 `protobuf:"bytes,21,opt,name=health_response,json=healthResponse,proto3,oneof"`
}

type EnvelopeV1_Shutdown struct {
	Shutdown *ShutdownV1 `protobuf:"bytes,30,opt,name=shutdown,proto3,oneof"`
}

type EnvelopeV1_ShutdownAck struct {
	ShutdownAck *ShutdownAckV1 `protobuf:"bytes,31,opt,name=shutdown_ack,json=shutdownAck,proto3,oneof"`
}

type EnvelopeV1_CommandRequest struct {
	CommandRequest *CommandRequestV1 `protobuf:"bytes,40,opt,name=command_request,json=commandRequest,proto3,oneof"`
}

type EnvelopeV1_CommandResponse struct {
	CommandResponse *CommandResponseV1 `protobuf:"bytes,41,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

type EnvelopeV1_HookRequest struct {
	HookRequest *HookRequestV1 `protobuf:"bytes,50,opt,name=hook_request,json=hookRequest,proto3,oneof"`
}

type EnvelopeV1_HookResponse struct {
	HookResponse *HookResponseV1 `protobuf:"bytes,51,opt,name=hook_response,json=hookResponse,proto3,oneof"`
}

type EnvelopeV1_ServerQuery struct {
	ServerQuery *ServerQueryV1 `protobuf:"bytes,60,opt,name=server_query,json=serverQuery,proto3,oneof"`
}

type EnvelopeV1_ServerQueryResponse struct {
	ServerQueryResponse *ServerQueryResponseV1 `protobuf:"bytes,61,opt,name=server_query_response,json=serverQueryResponse,proto3,oneof"`
}

func (*EnvelopeV1_Register) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_RegisterAck) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_HealthCheck) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_HealthResponse) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_Shutdown) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_ShutdownAck) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_CommandRequest) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_CommandResponse) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_HookRequest) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_HookResponse) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_ServerQuery) isEnvelopeV1_Payload() {}

func (*EnvelopeV1_ServerQueryResponse) isEnvelopeV1_Payload() {}

// RegisterV1 is sent by the plugin after connecting to announce capabilities.
type RegisterV1 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Critical        bool                   `protobuf:"varint,3,opt,name=critical,proto3" json:"critical,omitempty"`
	Commands        []*CommandDeclV1       `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`                                      // commands this plugin provides
	Priority        int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                     // plugin priority (lower = higher priority)
	Hooks           []*HookDeclV1          `protobuf:"bytes,6,rep,name=hooks,proto3" json:"hooks,omitempty"`                                            // hooks this plugin wants to intercept
	RequestedScopes []string               `protobuf:"bytes,7,rep,name=requested_scopes,json=requestedScopes,proto3" json:"requested_scopes,omitempty"` // scopes the plugin requests (e.g. "read", "write", "hook:pre", "keys:prefix:*")
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterV1) Reset() {
	*x = RegisterV1{}
	mi := &file_gcpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterV1) ProtoMessage() {}

func (x *RegisterV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterV1.ProtoReflect.Descriptor instead.
func (*RegisterV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterV1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterV1) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterV1) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

func (x *RegisterV1) GetCommands() []*CommandDeclV1 {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *RegisterV1) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RegisterV1) GetHooks() []*HookDeclV1 {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *RegisterV1) GetRequestedScopes() []string {
	if x != nil {
		return x.RequestedScopes
	}
	return nil
}

// CommandDeclV1 declares a single command a plugin can handle.
type CommandDeclV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`              // command name, e.g. "PUBLISH" or "QUERY"
	Namespaced    bool                   `protobuf:"varint,2,opt,name=namespaced,proto3" json:"namespaced,omitempty"` // true = REX (PLUGIN:CMD), false = main namespace
	MinArgs       int32                  `protobuf:"varint,3,opt,name=min_args,json=minArgs,proto3" json:"min_args,omitempty"`
	MaxArgs       int32                  `protobuf:"varint,4,opt,name=max_args,json=maxArgs,proto3" json:"max_args,omitempty"` // -1 = unlimited
	Readonly      bool                   `protobuf:"varint,5,opt,name=readonly,proto3" json:"readonly,omitempty"`              // hint: command does not mutate state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDeclV1) Reset() {
	*x = CommandDeclV1{}
	mi := &file_gcpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDeclV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDeclV1) ProtoMessage() {}

func (x *CommandDeclV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDeclV1.ProtoReflect.Descriptor instead.
func (*CommandDeclV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{2}
}

func (x *CommandDeclV1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandDeclV1) GetNamespaced() bool {
	if x != nil {
		return x.Namespaced
	}
	return false
}

func (x *CommandDeclV1) GetMinArgs() int32 {
	if x != nil {
		return x.MinArgs
	}
	return 0
}

func (x *CommandDeclV1) GetMaxArgs() int32 {
	if x != nil {
		return x.MaxArgs
	}
	return 0
}

func (x *CommandDeclV1) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

// HookDeclV1 declares a hook a plugin wants to intercept.
type HookDeclV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`                       // "SET", "GET", "*" (exact or wildcard)
	Phase         HookPhaseV1            `protobuf:"varint,2,opt,name=phase,proto3,enum=gcpc.v1.HookPhaseV1" json:"phase,omitempty"` // when the hook fires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookDeclV1) Reset() {
	*x = HookDeclV1{}
	mi := &file_gcpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookDeclV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookDeclV1) ProtoMessage() {}

func (x *HookDeclV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookDeclV1.ProtoReflect.Descriptor instead.
func (*HookDeclV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{3}
}

func (x *HookDeclV1) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *HookDeclV1) GetPhase() HookPhaseV1 {
	if x != nil {
		return x.Phase
	}
	return HookPhaseV1_HOOK_PHASE_UNSPECIFIED
}

// RegisterAckV1 is the server's response to a RegisterV1 message.
type RegisterAckV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	GrantedScopes []string               `protobuf:"bytes,3,rep,name=granted_scopes,json=grantedScopes,proto3" json:"granted_scopes,omitempty"` // scopes actually granted (intersection of requested and allowed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAckV1) Reset() {
	*x = RegisterAckV1{}
	mi := &file_gcpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAckV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAckV1) ProtoMessage() {}

func (x *RegisterAckV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAckV1.ProtoReflect.Descriptor instead.
func (*RegisterAckV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAckV1) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterAckV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegisterAckV1) GetGrantedScopes() []string {
	if x != nil {
		return x.GrantedScopes
	}
	return nil
}

// HealthCheckV1 is sent by the server periodically to verify plugin liveness.
type HealthCheckV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckV1) Reset() {
	*x = HealthCheckV1{}
	mi := &file_gcpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckV1) ProtoMessage() {}

func (x *HealthCheckV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckV1.ProtoReflect.Descriptor instead.
func (*HealthCheckV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckV1) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthResponseV1 is the plugin's reply to a HealthCheckV1.
type HealthResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponseV1) Reset() {
	*x = HealthResponseV1{}
	mi := &file_gcpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponseV1) ProtoMessage() {}

func (x *HealthResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponseV1.ProtoReflect.Descriptor instead.
func (*HealthResponseV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponseV1) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponseV1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ShutdownV1 is sent by the server to request graceful plugin termination.
type ShutdownV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeadlineNs    uint64                 `protobuf:"varint,1,opt,name=deadline_ns,json=deadlineNs,proto3" json:"deadline_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownV1) Reset() {
	*x = ShutdownV1{}
	mi := &file_gcpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownV1) ProtoMessage() {}

func (x *ShutdownV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownV1.ProtoReflect.Descriptor instead.
func (*ShutdownV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{7}
}

func (x *ShutdownV1) GetDeadlineNs() uint64 {
	if x != nil {
		return x.DeadlineNs
	}
	return 0
}

// ShutdownAckV1 is the plugin's acknowledgement of a ShutdownV1 request.
type ShutdownAckV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownAckV1) Reset() {
	*x = ShutdownAckV1{}
	mi := &file_gcpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownAckV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownAckV1) ProtoMessage() {}

func (x *ShutdownAckV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownAckV1.ProtoReflect.Descriptor instead.
func (*ShutdownAckV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{8}
}

// CommandRequestV1 is sent by the server to invoke a plugin command.
type CommandRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                                                                             // resolved command name (e.g. "PUBLISH")
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`                                                                                   // command arguments as strings
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                        // correlation ID for multiplexed responses
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // REX metadata (bare keys, no shared.rex. prefix)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequestV1) Reset() {
	*x = CommandRequestV1{}
	mi := &file_gcpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequestV1) ProtoMessage() {}

func (x *CommandRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequestV1.ProtoReflect.Descriptor instead.
func (*CommandRequestV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{9}
}

func (x *CommandRequestV1) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequestV1) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandRequestV1) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandRequestV1) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CommandResponseV1 is the plugin's response to a CommandRequestV1.
type CommandResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Result        *ResultV1              `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponseV1) Reset() {
	*x = CommandResponseV1{}
	mi := &file_gcpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponseV1) ProtoMessage() {}

func (x *CommandResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponseV1.ProtoReflect.Descriptor instead.
func (*CommandResponseV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{10}
}

func (x *CommandResponseV1) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResponseV1) GetResult() *ResultV1 {
	if x != nil {
		return x.Result
	}
	return nil
}

// HookRequestV1 is sent by the server when a hook fires.
type HookRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // correlation ID
	Phase         HookPhaseV1            `protobuf:"varint,2,opt,name=phase,proto3,enum=gcpc.v1.HookPhaseV1" json:"phase,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"` // the command being hooked (e.g. "SET")
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	ResultValue   string                 `protobuf:"bytes,5,opt,name=result_value,json=resultValue,proto3" json:"result_value,omitempty"`                                                  // post-hook only: serialized result
	ResultError   string                 `protobuf:"bytes,6,opt,name=result_error,json=resultError,proto3" json:"result_error,omitempty"`                                                  // post-hook only: error string if any
	Context       map[string]string      `protobuf:"bytes,7,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`   // accumulated hook context (server + own namespace + shared)
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // REX metadata (bare keys, no shared.rex. prefix)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequestV1) Reset() {
	*x = HookRequestV1{}
	mi := &file_gcpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequestV1) ProtoMessage() {}

func (x *HookRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequestV1.ProtoReflect.Descriptor instead.
func (*HookRequestV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{11}
}

func (x *HookRequestV1) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HookRequestV1) GetPhase() HookPhaseV1 {
	if x != nil {
		return x.Phase
	}
	return HookPhaseV1_HOOK_PHASE_UNSPECIFIED
}

func (x *HookRequestV1) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HookRequestV1) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *HookRequestV1) GetResultValue() string {
	if x != nil {
		return x.ResultValue
	}
	return ""
}

func (x *HookRequestV1) GetResultError() string {
	if x != nil {
		return x.ResultError
	}
	return ""
}

func (x *HookRequestV1) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *HookRequestV1) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HookResponseV1 is the plugin's response to a HookRequestV1.
// Only required for critical plugin hooks (non-critical are fire-and-forget).
type HookResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Deny          bool                   `protobuf:"varint,2,opt,name=deny,proto3" json:"deny,omitempty"` // pre-hook only: true = abort the command
	DenyReason    string                 `protobuf:"bytes,3,opt,name=deny_reason,json=denyReason,proto3" json:"deny_reason,omitempty"`
	ContextValues map[string]string      `protobuf:"bytes,4,rep,name=context_values,json=contextValues,proto3" json:"context_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // pre-hook: values to add to command context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponseV1) Reset() {
	*x = HookResponseV1{}
	mi := &file_gcpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponseV1) ProtoMessage() {}

func (x *HookResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponseV1.ProtoReflect.Descriptor instead.
func (*HookResponseV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{12}
}

func (x *HookResponseV1) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HookResponseV1) GetDeny() bool {
	if x != nil {
		return x.Deny
	}
	return false
}

func (x *HookResponseV1) GetDenyReason() string {
	if x != nil {
		return x.DenyReason
	}
	return ""
}

func (x *HookResponseV1) GetContextValues() map[string]string {
	if x != nil {
		return x.ContextValues
	}
	return nil
}

// ResultV1 is a recursive RESP-like value tree for command results.
type ResultV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ResultV1_SimpleString
	//	*ResultV1_Error
	//	*ResultV1_Integer
	//	*ResultV1_BulkString
	//	*ResultV1_IsNull
	//	*ResultV1_DoubleVal
	//	*ResultV1_Array
	//	*ResultV1_MapVal
	Value         isResultV1_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultV1) Reset() {
	*x = ResultV1{}
	mi := &file_gcpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultV1) ProtoMessage() {}

func (x *ResultV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultV1.ProtoReflect.Descriptor instead.
func (*ResultV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{13}
}

func (x *ResultV1) GetValue() isResultV1_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ResultV1) GetSimpleString() string {
	if x != nil {
		if x, ok := x.Value.(*ResultV1_SimpleString); ok {
			return x.SimpleString
		}
	}
	return ""
}

func (x *ResultV1) GetError() string {
	if x != nil {
		if x, ok := x.Value.(*ResultV1_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *ResultV1) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Value.(*ResultV1_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *ResultV1) GetBulkString() string {
	if x != nil {
		if x, ok := x.Value.(*ResultV1_BulkString); ok {
			return x.BulkString
		}
	}
	return ""
}

func (x *ResultV1) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Value.(*ResultV1_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *ResultV1) GetDoubleVal() float64 {
	if x != nil {
		if x, ok := x.Value.(*ResultV1_DoubleVal); ok {
			return x.DoubleVal
		}
	}
	return 0
}

func (x *ResultV1) GetArray() *ResultArrayV1 {
	if x != nil {
		if x, ok := x.Value.(*ResultV1_Array); ok {
			return x.Array
		}
	}
	return nil
}

func (x *ResultV1) GetMapVal() *ResultMapV1 {
	if x != nil {
		if x, ok := x.Value.(*ResultV1_MapVal); ok {
			return x.MapVal
		}
	}
	return nil
}

type isResultV1_Value interface {
	isResultV1_Value()
}

type ResultV1_SimpleString struct {
	SimpleString string `protobuf:"bytes,1,opt,name=simple_string,json=simpleString,proto3,oneof"` // RESP simple string (+OK)
}

type ResultV1_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // RESP error (-ERR ...)
}

type ResultV1_Integer struct {
	Integer int64 `protobuf:"varint,3,opt,name=integer,proto3,oneof"` // RESP integer (:42)
}

type ResultV1_BulkString struct {
	BulkString string `protobuf:"bytes,4,opt,name=bulk_string,json=bulkString,proto3,oneof"` // RESP bulk string ($...)
}

type ResultV1_IsNull struct {
	IsNull bool `protobuf:"varint,5,opt,name=is_null,json=isNull,proto3,oneof"` // RESP null
}

type ResultV1_DoubleVal struct {
	DoubleVal float64 `protobuf:"fixed64,6,opt,name=double_val,json=doubleVal,proto3,oneof"` // RESP3 double
}

type ResultV1_Array struct {
	Array *ResultArrayV1 `protobuf:"bytes,7,opt,name=array,proto3,oneof"` // RESP array (*...)
}

type ResultV1_MapVal struct {
	MapVal *ResultMapV1 `protobuf:"bytes,8,opt,name=map_val,json=mapVal,proto3,oneof"` // RESP3 map
}

func (*ResultV1_SimpleString) isResultV1_Value() {}

func (*ResultV1_Error) isResultV1_Value() {}

func (*ResultV1_Integer) isResultV1_Value() {}

func (*ResultV1_BulkString) isResultV1_Value() {}

func (*ResultV1_IsNull) isResultV1_Value() {}

func (*ResultV1_DoubleVal) isResultV1_Value() {}

func (*ResultV1_Array) isResultV1_Value() {}

func (*ResultV1_MapVal) isResultV1_Value() {}

// ResultArrayV1 holds an ordered list of results.
type ResultArrayV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*ResultV1            `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultArrayV1) Reset() {
	*x = ResultArrayV1{}
	mi := &file_gcpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultArrayV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultArrayV1) ProtoMessage() {}

func (x *ResultArrayV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultArrayV1.ProtoReflect.Descriptor instead.
func (*ResultArrayV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{14}
}

func (x *ResultArrayV1) GetElements() []*ResultV1 {
	if x != nil {
		return x.Elements
	}
	return nil
}

// ResultMapV1 holds key-value pairs for RESP3 map responses.
type ResultMapV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ResultEntryV1       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultMapV1) Reset() {
	*x = ResultMapV1{}
	mi := &file_gcpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultMapV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMapV1) ProtoMessage() {}

func (x *ResultMapV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMapV1.ProtoReflect.Descriptor instead.
func (*ResultMapV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{15}
}

func (x *ResultMapV1) GetEntries() []*ResultEntryV1 {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ResultEntryV1 is a single key-value pair in a ResultMapV1.
type ResultEntryV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *ResultV1              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultEntryV1) Reset() {
	*x = ResultEntryV1{}
	mi := &file_gcpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultEntryV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultEntryV1) ProtoMessage() {}

func (x *ResultEntryV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultEntryV1.ProtoReflect.Descriptor instead.
func (*ResultEntryV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{16}
}

func (x *ResultEntryV1) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResultEntryV1) GetValue() *ResultV1 {
	if x != nil {
		return x.Value
	}
	return nil
}

// ServerQueryV1 is sent by a plugin to query server state.
type ServerQueryV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // correlation ID for response matching
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`                          // query topic: "health", "plugins", "stats"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerQueryV1) Reset() {
	*x = ServerQueryV1{}
	mi := &file_gcpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerQueryV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerQueryV1) ProtoMessage() {}

func (x *ServerQueryV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerQueryV1.ProtoReflect.Descriptor instead.
func (*ServerQueryV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{17}
}

func (x *ServerQueryV1) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerQueryV1) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// ServerQueryResponseV1 is the server's response to a ServerQueryV1.
type ServerQueryResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // topic-specific key-value data
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                                                         // non-empty if query failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerQueryResponseV1) Reset() {
	*x = ServerQueryResponseV1{}
	mi := &file_gcpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerQueryResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerQueryResponseV1) ProtoMessage() {}

func (x *ServerQueryResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_gcpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerQueryResponseV1.ProtoReflect.Descriptor instead.
func (*ServerQueryResponseV1) Descriptor() ([]byte, []int) {
	return file_gcpc_proto_rawDescGZIP(), []int{18}
}

func (x *ServerQueryResponseV1) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerQueryResponseV1) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServerQueryResponseV1) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_gcpc_proto protoreflect.FileDescriptor

const file_gcpc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"gcpc.proto\x12\agcpc.v1\"\xc3\x06\n" +
	"\n" +
	"EnvelopeV1\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x121\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x13.gcpc.v1.RegisterV1H\x00R\bregister\x12;\n" +
	"\fregister_ack\x18\v \x01(\v2\x16.gcpc.v1.RegisterAckV1H\x00R\vregisterAck\x12;\n" +
	"\fhealth_check\x18\x14 \x01(\v2\x16.gcpc.v1.HealthCheckV1H\x00R\vhealthCheck\x12D\n" +
	"\x0fhealth_response\x18\x15 \x01(\v2\x19.gcpc.v1.HealthResponseV1H\x00R\x0ehealthResponse\x121\n" +
	"\bshutdown\x18\x1e \x01(\v2\x13.gcpc.v1.ShutdownV1H\x00R\bshutdown\x12;\n" +
	"\fshutdown_ack\x18\x1f \x01(\v2\x16.gcpc.v1.ShutdownAckV1H\x00R\vshutdownAck\x12D\n" +
	"\x0fcommand_request\x18( \x01(\v2\x19.gcpc.v1.CommandRequestV1H\x00R\x0ecommandRequest\x12G\n" +
	"\x10command_response\x18) \x01(\v2\x1a.gcpc.v1.CommandResponseV1H\x00R\x0fcommandResponse\x12;\n" +
	"\fhook_request\x182 \x01(\v2\x16.gcpc.v1.HookRequestV1H\x00R\vhookRequest\x12>\n" +
	"\rhook_response\x183 \x01(\v2\x17.gcpc.v1.HookResponseV1H\x00R\fhookResponse\x12;\n" +
	"\fserver_query\x18< \x01(\v2\x16.gcpc.v1.ServerQueryV1H\x00R\vserverQuery\x12T\n" +
	"\x15server_query_response\x18= \x01(\v2\x1e.gcpc.v1.ServerQueryResponseV1H\x00R\x13serverQueryResponseB\t\n" +
	"\apayload\"\xfc\x01\n" +
	"\n" +
	"RegisterV1\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bcritical\x18\x03 \x01(\bR\bcritical\x122\n" +
	"\bcommands\x18\x04 \x03(\v2\x16.gcpc.v1.CommandDeclV1R\bcommands\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12)\n" +
	"\x05hooks\x18\x06 \x03(\v2\x13.gcpc.v1.HookDeclV1R\x05hooks\x12)\n" +
	"\x10requested_scopes\x18\a \x03(\tR\x0frequestedScopes\"\x95\x01\n" +
	"\rCommandDeclV1\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"namespaced\x18\x02 \x01(\bR\n" +
	"namespaced\x12\x19\n" +
	"\bmin_args\x18\x03 \x01(\x05R\aminArgs\x12\x19\n" +
	"\bmax_args\x18\x04 \x01(\x05R\amaxArgs\x12\x1a\n" +
	"\breadonly\x18\x05 \x01(\bR\breadonly\"R\n" +
	"\n" +
	"HookDeclV1\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12*\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x14.gcpc.v1.HookPhaseV1R\x05phase\"j\n" +
	"\rRegisterAckV1\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0egranted_scopes\x18\x03 \x03(\tR\rgrantedScopes\"-\n" +
	"\rHealthCheckV1\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\":\n" +
	"\x10HealthResponseV1\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"-\n" +
	"\n" +
	"ShutdownV1\x12\x1f\n" +
	"\vdeadline_ns\x18\x01 \x01(\x04R\n" +
	"deadlineNs\"\x0f\n" +
	"\rShutdownAckV1\"\xe1\x01\n" +
	"\x10CommandRequestV1\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.gcpc.v1.CommandRequestV1.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x11CommandResponseV1\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12)\n" +
	"\x06result\x18\x02 \x01(\v2\x11.gcpc.v1.ResultV1R\x06result\"\xc8\x03\n" +
	"\rHookRequestV1\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12*\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x14.gcpc.v1.HookPhaseV1R\x05phase\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12!\n" +
	"\fresult_value\x18\x05 \x01(\tR\vresultValue\x12!\n" +
	"\fresult_error\x18\x06 \x01(\tR\vresultError\x12=\n" +
	"\acontext\x18\a \x03(\v2#.gcpc.v1.HookRequestV1.ContextEntryR\acontext\x12@\n" +
	"\bmetadata\x18\b \x03(\v2$.gcpc.v1.HookRequestV1.MetadataEntryR\bmetadata\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x0eHookResponseV1\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04deny\x18\x02 \x01(\bR\x04deny\x12\x1f\n" +
	"\vdeny_reason\x18\x03 \x01(\tR\n" +
	"denyReason\x12Q\n" +
	"\x0econtext_values\x18\x04 \x03(\v2*.gcpc.v1.HookResponseV1.ContextValuesEntryR\rcontextValues\x1a@\n" +
	"\x12ContextValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x02\n" +
	"\bResultV1\x12%\n" +
	"\rsimple_string\x18\x01 \x01(\tH\x00R\fsimpleString\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x12\x1a\n" +
	"\ainteger\x18\x03 \x01(\x03H\x00R\ainteger\x12!\n" +
	"\vbulk_string\x18\x04 \x01(\tH\x00R\n" +
	"bulkString\x12\x19\n" +
	"\ais_null\x18\x05 \x01(\bH\x00R\x06isNull\x12\x1f\n" +
	"\n" +
	"double_val\x18\x06 \x01(\x01H\x00R\tdoubleVal\x12.\n" +
	"\x05array\x18\a \x01(\v2\x16.gcpc.v1.ResultArrayV1H\x00R\x05array\x12/\n" +
	"\amap_val\x18\b \x01(\v2\x14.gcpc.v1.ResultMapV1H\x00R\x06mapValB\a\n" +
	"\x05value\">\n" +
	"\rResultArrayV1\x12-\n" +
	"\belements\x18\x01 \x03(\v2\x11.gcpc.v1.ResultV1R\belements\"?\n" +
	"\vResultMapV1\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.gcpc.v1.ResultEntryV1R\aentries\"J\n" +
	"\rResultEntryV1\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.gcpc.v1.ResultV1R\x05value\"D\n" +
	"\rServerQueryV1\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\xc3\x01\n" +
	"\x15ServerQueryResponseV1\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12<\n" +
	"\x04data\x18\x02 \x03(\v2(.gcpc.v1.ServerQueryResponseV1.DataEntryR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*R\n" +
	"\vHookPhaseV1\x12\x1a\n" +
	"\x16HOOK_PHASE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eHOOK_PHASE_PRE\x10\x01\x12\x13\n" +
	"\x0fHOOK_PHASE_POST\x10\x02B\x17Z\x15gocache/proto/gcpc/v1b\x06proto3"

var (
	file_gcpc_proto_rawDescOnce sync.Once
	file_gcpc_proto_rawDescData []byte
)

func file_gcpc_proto_rawDescGZIP() []byte {
	file_gcpc_proto_rawDescOnce.Do(func() {
		file_gcpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gcpc_proto_rawDesc), len(file_gcpc_proto_rawDesc)))
	})
	return file_gcpc_proto_rawDescData
}

var file_gcpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gcpc_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_gcpc_proto_goTypes = []any{
	(HookPhaseV1)(0),              // 0: gcpc.v1.HookPhaseV1
	(*EnvelopeV1)(nil),            // 1: gcpc.v1.EnvelopeV1
	(*RegisterV1)(nil),            // 2: gcpc.v1.RegisterV1
	(*CommandDeclV1)(nil),         // 3: gcpc.v1.CommandDeclV1
	(*HookDeclV1)(nil),            // 4: gcpc.v1.HookDeclV1
	(*RegisterAckV1)(nil),         // 5: gcpc.v1.RegisterAckV1
	(*HealthCheckV1)(nil),         // 6: gcpc.v1.HealthCheckV1
	(*HealthResponseV1)(nil),      // 7: gcpc.v1.HealthResponseV1
	(*ShutdownV1)(nil),            // 8: gcpc.v1.ShutdownV1
	(*ShutdownAckV1)(nil),         // 9: gcpc.v1.ShutdownAckV1
	(*CommandRequestV1)(nil),      // 10: gcpc.v1.CommandRequestV1
	(*CommandResponseV1)(nil),     // 11: gcpc.v1.CommandResponseV1
	(*HookRequestV1)(nil),         // 12: gcpc.v1.HookRequestV1
	(*HookResponseV1)(nil),        // 13: gcpc.v1.HookResponseV1
	(*ResultV1)(nil),              // 14: gcpc.v1.ResultV1
	(*ResultArrayV1)(nil),         // 15: gcpc.v1.ResultArrayV1
	(*ResultMapV1)(nil),           // 16: gcpc.v1.ResultMapV1
	(*ResultEntryV1)(nil),         // 17: gcpc.v1.ResultEntryV1
	(*ServerQueryV1)(nil),         // 18: gcpc.v1.ServerQueryV1
	(*ServerQueryResponseV1)(nil), // 19: gcpc.v1.ServerQueryResponseV1
	nil,                           // 20: gcpc.v1.CommandRequestV1.MetadataEntry
	nil,                           // 21: gcpc.v1.HookRequestV1.ContextEntry
	nil,                           // 22: gcpc.v1.HookRequestV1.MetadataEntry
	nil,                           // 23: gcpc.v1.HookResponseV1.ContextValuesEntry
	nil,                           // 24: gcpc.v1.ServerQueryResponseV1.DataEntry
}
var file_gcpc_proto_depIdxs = []int32{
	2,  // 0: gcpc.v1.EnvelopeV1.register:type_name -> gcpc.v1.RegisterV1
	5,  // 1: gcpc.v1.EnvelopeV1.register_ack:type_name -> gcpc.v1.RegisterAckV1
	6,  // 2: gcpc.v1.EnvelopeV1.health_check:type_name -> gcpc.v1.HealthCheckV1
	7,  // 3: gcpc.v1.EnvelopeV1.health_response:type_name -> gcpc.v1.HealthResponseV1
	8,  // 4: gcpc.v1.EnvelopeV1.shutdown:type_name -> gcpc.v1.ShutdownV1
	9,  // 5: gcpc.v1.EnvelopeV1.shutdown_ack:type_name -> gcpc.v1.ShutdownAckV1
	10, // 6: gcpc.v1.EnvelopeV1.command_request:type_name -> gcpc.v1.CommandRequestV1
	11, // 7: gcpc.v1.EnvelopeV1.command_response:type_name -> gcpc.v1.CommandResponseV1
	12, // 8: gcpc.v1.EnvelopeV1.hook_request:type_name -> gcpc.v1.HookRequestV1
	13, // 9: gcpc.v1.EnvelopeV1.hook_response:type_name -> gcpc.v1.HookResponseV1
	18, // 10: gcpc.v1.EnvelopeV1.server_query:type_name -> gcpc.v1.ServerQueryV1
	19, // 11: gcpc.v1.EnvelopeV1.server_query_response:type_name -> gcpc.v1.ServerQueryResponseV1
	3,  // 12: gcpc.v1.RegisterV1.commands:type_name -> gcpc.v1.CommandDeclV1
	4,  // 13: gcpc.v1.RegisterV1.hooks:type_name -> gcpc.v1.HookDeclV1
	0,  // 14: gcpc.v1.HookDeclV1.phase:type_name -> gcpc.v1.HookPhaseV1
	20, // 15: gcpc.v1.CommandRequestV1.metadata:type_name -> gcpc.v1.CommandRequestV1.MetadataEntry
	14, // 16: gcpc.v1.CommandResponseV1.result:type_name -> gcpc.v1.ResultV1
	0,  // 17: gcpc.v1.HookRequestV1.phase:type_name -> gcpc.v1.HookPhaseV1
	21, // 18: gcpc.v1.HookRequestV1.context:type_name -> gcpc.v1.HookRequestV1.ContextEntry
	22, // 19: gcpc.v1.HookRequestV1.metadata:type_name -> gcpc.v1.HookRequestV1.MetadataEntry
	23, // 20: gcpc.v1.HookResponseV1.context_values:type_name -> gcpc.v1.HookResponseV1.ContextValuesEntry
	15, // 21: gcpc.v1.ResultV1.array:type_name -> gcpc.v1.ResultArrayV1
	16, // 22: gcpc.v1.ResultV1.map_val:type_name -> gcpc.v1.ResultMapV1
	14, // 23: gcpc.v1.ResultArrayV1.elements:type_name -> gcpc.v1.ResultV1
	17, // 24: gcpc.v1.ResultMapV1.entries:type_name -> gcpc.v1.ResultEntryV1
	14, // 25: gcpc.v1.ResultEntryV1.value:type_name -> gcpc.v1.ResultV1
	24, // 26: gcpc.v1.ServerQueryResponseV1.data:type_name -> gcpc.v1.ServerQueryResponseV1.DataEntry
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_gcpc_proto_init() }
func file_gcpc_proto_init() {
	if File_gcpc_proto != nil {
		return
	}
	file_gcpc_proto_msgTypes[0].OneofWrappers = []any{
		(*EnvelopeV1_Register)(nil),
		(*EnvelopeV1_RegisterAck)(nil),
		(*EnvelopeV1_HealthCheck)(nil),
		(*EnvelopeV1_HealthResponse)(nil),
		(*EnvelopeV1_Shutdown)(nil),
		(*EnvelopeV1_ShutdownAck)(nil),
		(*EnvelopeV1_CommandRequest)(nil),
		(*EnvelopeV1_CommandResponse)(nil),
		(*EnvelopeV1_HookRequest)(nil),
		(*EnvelopeV1_HookResponse)(nil),
		(*EnvelopeV1_ServerQuery)(nil),
		(*EnvelopeV1_ServerQueryResponse)(nil),
	}
	file_gcpc_proto_msgTypes[13].OneofWrappers = []any{
		(*ResultV1_SimpleString)(nil),
		(*ResultV1_Error)(nil),
		(*ResultV1_Integer)(nil),
		(*ResultV1_BulkString)(nil),
		(*ResultV1_IsNull)(nil),
		(*ResultV1_DoubleVal)(nil),
		(*ResultV1_Array)(nil),
		(*ResultV1_MapVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcpc_proto_rawDesc), len(file_gcpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcpc_proto_goTypes,
		DependencyIndexes: file_gcpc_proto_depIdxs,
		EnumInfos:         file_gcpc_proto_enumTypes,
		MessageInfos:      file_gcpc_proto_msgTypes,
	}.Build()
	File_gcpc_proto = out.File
	file_gcpc_proto_goTypes = nil
	file_gcpc_proto_depIdxs = nil
}
